// ╭──────────────────────────╮
// │  dom.js                  │
// │  Builder selector        │
// │  defaults and cached DOM │
// │  reference collection    │
// ╰──────────────────────────╯
(function () {
  const namespace = window.PrintifyLabelBuilder = window.PrintifyLabelBuilder || {};

  // The builder still boots in a plain-script browser environment, so these
  // selector defaults are the stable contract between HTML and JS modules.
  const defaultSettings = {
    rootSelector: '#labelBuilder',
    titleSelector: '#labelBuilderTitle',
    copySelector: '#labelBuilderCopy',
    sizeSelector: '#labelBuilderSize',
    enterConfirmSelector: '#labelBuilderEnterConfirm',
    closeSelector: '#labelBuilderClose',
    cancelSelector: '#labelBuilderCancel',
    resetSelector: '#labelBuilderReset',
    printSelector: '#labelBuilderPrint',
    previewSelector: '[data-role="label-builder-preview"]',
    monochromePreviewSelector: '#labelBuilderMonochromePreview',
    monochromePreviewShellSelector: '#labelBuilderMonochromePreviewShell',
    monochromePreviewImageSelector: '#labelBuilderMonochromePreviewImage',
    copiesSelector: '#labelBuilderCopies',
    textCardSelector: '#labelBuilderTextCard',
    imageCardSelector: '#labelBuilderImageCard',
    qrCardSelector: '#labelBuilderQrCard',
    fontSelector: '#labelBuilderFont',
    fontSizeSelector: '#labelBuilderFontSize',
    autoFitSelector: '#labelBuilderAutoFit',
    autoFitWidthSelector: '#labelBuilderAutoFitWidth',
    textSerialEnabledSelector: '#labelBuilderTextSerialEnabled',
    textSerialValueSelector: '#labelBuilderTextSerialValue',
    textSerialDigitsSelector: '#labelBuilderTextSerialDigits',
    textSerialValueFieldSelector: '#labelBuilderTextSerialValueField',
    qrFormatSelector: '#labelBuilderQrFormat',
    qrTextSelector: '#labelBuilderQrText',
    codeSerialEnabledSelector: '#labelBuilderCodeSerialEnabled',
    codeSerialValueSelector: '#labelBuilderCodeSerialValue',
    codeSerialDigitsSelector: '#labelBuilderCodeSerialDigits',
    codeSerialValueFieldSelector: '#labelBuilderCodeSerialValueField',
    imageInputSelector: '#labelBuilderImageInput',
    addImageSelector: '#labelBuilderAddImage',
    canvasWrapSelector: '.printify-builder__canvas-wrap',
    canvasShellSelector: '.printify-builder__canvas-shell',
    undoButtonSelector: '#labelBuilderUndo',
    redoButtonSelector: '#labelBuilderRedo',
    addTextSelector: '#labelBuilderAddText',
    addQrSelector: '#labelBuilderAddQr',
    templatesButtonSelector: '#labelBuilderTemplatesButton',
    templateModalSelector: '#labelBuilderTemplatesModal',
    templateModalCloseSelector: '#labelBuilderTemplatesClose',
    templateLocalTabSelector: '#labelBuilderTemplatesTabLocal',
    templateRemoteTabSelector: '#labelBuilderTemplatesTabRemote',
    templateRemoteToolsSelector: '#labelBuilderTemplatesRemoteTools',
    templatePathSelector: '#labelBuilderTemplatesPath',
    templateUpSelector: '#labelBuilderTemplatesUp',
    templateNewFolderSelector: '#labelBuilderTemplatesNewFolder',
    templateRefreshSelector: '#labelBuilderTemplatesRefresh',
    templateNameSelector: '#labelBuilderTemplateName',
    templateSaveLocalSelector: '#labelBuilderTemplateSaveLocal',
    templateSaveRemoteSelector: '#labelBuilderTemplateSaveRemote',
    templateGridSelector: '#labelBuilderTemplatesGrid',
    templateEmptySelector: '#labelBuilderTemplatesEmpty',
    templateFeedbackSelector: '#labelBuilderTemplatesFeedback',
    tapeControlsSelector: '#labelBuilderTapeControls',
    tapeWidthSelector: '#labelBuilderTapeWidth',
    tapeLengthSelector: '#labelBuilderTapeLength',
    tapeAutoLengthSelector: '#labelBuilderTapeAutoLength',
    invertWrapSelector: '#labelBuilderInvertWrap',
    invertPrintSelector: '#labelBuilderInvertPrint',
    imageBoxCenterSelector: '#labelBuilderImageBoxCenter',
    imageBoxFillSelector: '#labelBuilderImageBoxFill',
    alignLeftSelector: '#labelBuilderAlignLeft',
    alignCenterSelector: '#labelBuilderAlignCenter',
    alignRightSelector: '#labelBuilderAlignRight',
    verticalTopSelector: '#labelBuilderVerticalTop',
    verticalMiddleSelector: '#labelBuilderVerticalMiddle',
    verticalBottomSelector: '#labelBuilderVerticalBottom',
    boxCenterSelector: '#labelBuilderBoxCenter',
    boxFillSelector: '#labelBuilderBoxFill',
    codeBoxCenterSelector: '#labelBuilderCodeBoxCenter',
    codeBoxFillSelector: '#labelBuilderCodeBoxFill',
    canvasId: 'labelCanvas',
    onPrint: async () => {},
    onError: () => {},
    getMonochromePreviewFields: () => ({}),
    getInvertPrintEnabled: () => false,
    setInvertPrintEnabled: () => {},
    getSavedFontFamily: () => '',
    setSavedFontFamily: () => {},
    closeOnPrint: true,
  };

  const createBuilderRefs = settings => {
    const root = document.querySelector(settings.rootSelector);

    // Query once up front so later modules can work with a shared refs object
    // instead of re-querying the DOM throughout canvas and preview flows.
    return {
      root,
      title: root?.querySelector(settings.titleSelector),
      copy: root?.querySelector(settings.copySelector),
      size: root?.querySelector(settings.sizeSelector),
      enterConfirm: root?.querySelector(settings.enterConfirmSelector),
      closeButton: root?.querySelector(settings.closeSelector),
      cancelButton: root?.querySelector(settings.cancelSelector),
      resetButton: root?.querySelector(settings.resetSelector),
      printButton: root?.querySelector(settings.printSelector),
      previewButtons: Array.from(root?.querySelectorAll(settings.previewSelector) || []),
      monochromePreviewButton: root?.querySelector(settings.monochromePreviewSelector),
      monochromePreviewShell: root?.querySelector(settings.monochromePreviewShellSelector),
      monochromePreviewImage: root?.querySelector(settings.monochromePreviewImageSelector),
      copiesInput: root?.querySelector(settings.copiesSelector),
      textCard: root?.querySelector(settings.textCardSelector),
      imageCard: root?.querySelector(settings.imageCardSelector),
      qrCard: root?.querySelector(settings.qrCardSelector),
      fontSelect: root?.querySelector(settings.fontSelector),
      fontSizeInput: root?.querySelector(settings.fontSizeSelector),
      autoFitInput: root?.querySelector(settings.autoFitSelector),
      autoFitWidthInput: root?.querySelector(settings.autoFitWidthSelector),
      textSerialEnabledInput: root?.querySelector(settings.textSerialEnabledSelector),
      textSerialValueInput: root?.querySelector(settings.textSerialValueSelector),
      textSerialDigitsInput: root?.querySelector(settings.textSerialDigitsSelector),
      textSerialValueField: root?.querySelector(settings.textSerialValueFieldSelector),
      qrFormatSelect: root?.querySelector(settings.qrFormatSelector),
      qrTextInput: root?.querySelector(settings.qrTextSelector),
      codeSerialEnabledInput: root?.querySelector(settings.codeSerialEnabledSelector),
      codeSerialValueInput: root?.querySelector(settings.codeSerialValueSelector),
      codeSerialDigitsInput: root?.querySelector(settings.codeSerialDigitsSelector),
      codeSerialValueField: root?.querySelector(settings.codeSerialValueFieldSelector),
      imageInput: root?.querySelector(settings.imageInputSelector),
      addImageButton: root?.querySelector(settings.addImageSelector),
      canvasWrap: root?.querySelector(settings.canvasWrapSelector),
      canvasShell: root?.querySelector(settings.canvasShellSelector),
      undoButton: root?.querySelector(settings.undoButtonSelector),
      redoButton: root?.querySelector(settings.redoButtonSelector),
      addTextButton: root?.querySelector(settings.addTextSelector),
      addQrButton: root?.querySelector(settings.addQrSelector),
      templatesButton: root?.querySelector(settings.templatesButtonSelector),
      templateModal: root?.querySelector(settings.templateModalSelector),
      templateModalCloseButton: root?.querySelector(settings.templateModalCloseSelector),
      templateLocalTabButton: root?.querySelector(settings.templateLocalTabSelector),
      templateRemoteTabButton: root?.querySelector(settings.templateRemoteTabSelector),
      templateRemoteTools: root?.querySelector(settings.templateRemoteToolsSelector),
      templatePathLabel: root?.querySelector(settings.templatePathSelector),
      templateUpButton: root?.querySelector(settings.templateUpSelector),
      templateNewFolderButton: root?.querySelector(settings.templateNewFolderSelector),
      templateRefreshButton: root?.querySelector(settings.templateRefreshSelector),
      templateNameInput: root?.querySelector(settings.templateNameSelector),
      templateSaveLocalButton: root?.querySelector(settings.templateSaveLocalSelector),
      templateSaveRemoteButton: root?.querySelector(settings.templateSaveRemoteSelector),
      templateGrid: root?.querySelector(settings.templateGridSelector),
      templateEmpty: root?.querySelector(settings.templateEmptySelector),
      templateFeedback: root?.querySelector(settings.templateFeedbackSelector),
      tapeControls: root?.querySelector(settings.tapeControlsSelector),
      tapeWidthSelect: root?.querySelector(settings.tapeWidthSelector),
      tapeLengthInput: root?.querySelector(settings.tapeLengthSelector),
      tapeAutoLengthInput: root?.querySelector(settings.tapeAutoLengthSelector),
      invertWrap: root?.querySelector(settings.invertWrapSelector),
      invertPrintInput: root?.querySelector(settings.invertPrintSelector),
      imageBoxCenterButton: root?.querySelector(settings.imageBoxCenterSelector),
      imageBoxFillButton: root?.querySelector(settings.imageBoxFillSelector),
      alignLeftButton: root?.querySelector(settings.alignLeftSelector),
      alignCenterButton: root?.querySelector(settings.alignCenterSelector),
      alignRightButton: root?.querySelector(settings.alignRightSelector),
      verticalTopButton: root?.querySelector(settings.verticalTopSelector),
      verticalMiddleButton: root?.querySelector(settings.verticalMiddleSelector),
      verticalBottomButton: root?.querySelector(settings.verticalBottomSelector),
      boxCenterButton: root?.querySelector(settings.boxCenterSelector),
      boxFillButton: root?.querySelector(settings.boxFillSelector),
      codeBoxCenterButton: root?.querySelector(settings.codeBoxCenterSelector),
      codeBoxFillButton: root?.querySelector(settings.codeBoxFillSelector),
    };
  };

  namespace.dom = {
    createBuilderRefs,
    defaultSettings,
  };
}());
